# Generated by Django 4.1.7 on 2023-05-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='性')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='性 カナ')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='名 カナ')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('email', models.CharField(max_length=50, null=True, verbose_name='メールアドレス')),
                ('zipcode', models.CharField(max_length=50, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='番地以降')),
                ('entry_date', models.DateField(null=True, verbose_name='入社日')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('prefecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prefecture')),
            ],
        ),
    ]
