# Generated by Django 4.1.7 on 2023-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='メールアドレス')),
                ('bank_name', models.CharField(max_length=100, verbose_name='銀行名')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('account_number', models.CharField(max_length=20, verbose_name='口座番号')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='口座名義人')),
            ],
        ),
    ]
