# Generated by Django 4.1.7 on 2023-05-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtamaPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50, verbose_name='ログインID')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
                ('site_url', models.CharField(max_length=100, verbose_name='サイトURL')),
            ],
        ),
        migrations.CreateModel(
            name='AverageTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50, verbose_name='平均点')),
            ],
        ),
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_activity', models.CharField(max_length=50, verbose_name='部活動')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='学校名')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_category', models.CharField(max_length=50, verbose_name='小中高')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='生徒 性')),
                ('first_name', models.CharField(max_length=50, verbose_name='生徒 名')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='生徒 性 カナ')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='生徒 名 カナ')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='学年')),
                ('school_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='組')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話番号')),
                ('parent_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='保護者 性')),
                ('parent_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='保護者 名')),
                ('parent_last_name_kana', models.CharField(blank=True, max_length=50, null=True, verbose_name='保護者 性 カナ')),
                ('parent_first_name_kana', models.CharField(blank=True, max_length=50, null=True, verbose_name='保護者 名 カナ')),
                ('parent_phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='保護者電話番号')),
                ('parent_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='保護者 メールアドレス')),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='番地以降')),
                ('entry_date', models.DateField(null=True, verbose_name='入塾日')),
                ('expiration_date', models.DateField(null=True, verbose_name='有効期限')),
                ('stripe_data', models.CharField(max_length=250, null=True, verbose_name='Stripe決済情報')),
                ('introducer_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='紹介者\u3000性')),
                ('introducer_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='紹介者\u3000名')),
                ('unsubscribe_request', models.BooleanField(default=False, verbose_name='退塾申請')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudySapuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50, verbose_name='ログインID')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
                ('site_url', models.CharField(max_length=100, verbose_name='サイトURL')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='教科名')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='学年')),
                ('school_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.schoolcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category', models.CharField(max_length=50, verbose_name='テストの種類')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='学年')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
                ('school_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.schoolcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='テスト結果')),
                ('date', models.DateField(blank=True, null=True, verbose_name='テスト日')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.testcategory')),
            ],
        ),
    ]
