# Generated by Django 4.1.7 on 2023-05-07 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysapuri',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttarget',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city'),
        ),
        migrations.AddField(
            model_name='student',
            name='club_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.clubactivity'),
        ),
        migrations.AddField(
            model_name='student',
            name='prefecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prefecture'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='school_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.schoolcategory'),
        ),
        migrations.AddField(
            model_name='averagetestresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
        migrations.AddField(
            model_name='averagetestresult',
            name='test_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.testcategory'),
        ),
        migrations.AddField(
            model_name='atamaplus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
